### ISSUE TITLE
Apply DeploymentController in OS template

### ISSUE THREAD

**Issue by ALRubinger** [redhat-kontinuity/catapult#123]
@sabre1041 notes that he prefers using a DeploymentController to a ReplicationController in the OS template:

"it aligns with the OpenShift model as well as making the majority of the environment variables in the container as template parameters in case they would need to be overridden"

Let's make the switch.  Non-critical I *believe* as things seem to be working as-is, but we aim for best practices here in Developer Programs. :)

**Comment by sabre1041** [comment]
@ALRubinger Small correction as it should be a DeploymentConfig vs ReplicationController. A deploymentconfig will actually create a replicationcontroller which in turn will manage the lifecycle of pods for the particular deployment. I ran into issues during adb testing since both API objects are currently present in the template

**Comment by ALRubinger** [comment]
@sabre1041 Feel free to edit the issue description as needed; you got the plan here!

**Comment by ALRubinger** [comment]
a411672
