### ISSUE TITLE
Add annotations to enable build in OpenShift Console Overview page

### ISSUE THREAD

**Issue by ALRubinger** [redhat-kontinuity/catapult#133]
Following this example: 

  https://github.com/openshift/origin/blob/master/examples/jenkins/pipeline/pipelinetemplate.json#L23-L25

**Comment by ALRubinger** [comment]
Add to: https://github.com/redhat-kontinuity/catapult/blob/master/services/openshift-service-impl/src/main/resources/openshift-project-template.json

**Comment by ALRubinger** [comment]
1aa9fde

**Comment by ALRubinger** [comment]
Need to fix the name of the deployment used, see line note in commit.

**Comment by tnozicka** [comment]
@ALRubinger If this is the name of the deployment in (prod, test, dev) this might be a problem. The name of the deployment is defined in Jenkinsfile and catapult can not generally know that.

Do you remember the discussion about having 3 files in the repo (deployment.yaml, Jenkinsfile and pipeline.yaml). Moving pipeline.yaml file from control of catapult to the actual repo would solve that, since there it could be hardcoded (and make sense).

CC: @xcoulon

**Comment by ALRubinger** [comment]
fdaff9a

@tnozicka For now I have hardcoded this to expect a name of "jenkins", and +1 to your coupling these 3 files together in the repo after our first release.  For the time being we'll just all have to be aware that the name of the deployment in our Jenkinsfiles must be "jenkins".

**Comment by tnozicka** [comment]
@ALRubinger are you sure about that?

1. jenkins deployment is already there and it is the jenkins itself https://github.com/openshift/origin/blob/master/examples/jenkins/pipeline/jenkinstemplate.json#L59
2. this would make you not able to deploy more than one app per namespace (not sure how exactly catapult does it now?)

@ALRubinger I see your reluctance to changes right now.

**Comment by ALRubinger** [comment]
@tnozicka I'm not very *sure* of anything now, but am in this last week before release resistant to change. :)  So all in all I think whatever gets us to release is fine, and I'm comfortable wracking up some technical debt that we focus on paying off as the first order priority after Summit.

If I may invert the question: what would be your recommended course of action for this?

**Comment by tnozicka** [comment]
@ALRubinger Spoken like a manager :D Yes I am  fine with hard coding it for Summit, but:

- Do you actually want to see the pipeline under `jenkins` deployment and not the application deployment? This might work if we would have only one app for namespace without affecting Jenkinsfiles.

- If you want to have it under the actual deployment we need to change it to something else than `jenkins` because that one is already taken. e.g. `pipeline` and I would have to rename deployments in Jenkinsfile to `pipeline` as well.

**Comment by tnozicka** [comment]
Btw. we have 3 deployments from one pipeline so we should reference all 3 DCs there. And there can be generally different number of deployments depending on number of stages in Jenkinsfile. Just wanted to point that out, even it's probably after Summit.

**Comment by ALRubinger** [comment]
@tnozicka Ideally the pipeline build would be best shown under the actual deployment; that's what's being deployed.  In fact Jenkins is already taking up a lot of screen real estate for something the user shouldn't really care about as it's just fulfilling a tech need - building. :)  To be addressed for the fall in the UX.

But yeah, the build pipeline info to me is a property of the deployment not of the thing executing the build.

+1 on the eventual ideal for visualizing the 3 deployments and +1 on doing that after this release.

Reopened this issue pending new PRs and updated application Jenkinsfiles

**Comment by ALRubinger** [comment]
@tnozicka Keeping in mind: if my comment above means we don't get to see the visualized pipeline until the first build gets to the point where it creates the DeploymentConfig, then I'll opt for seeing the build on the Jenkins deployment.  Seeing it anywhere, even if it's not the idea place, is better than seeing it nowhere to start; the user need feedback right from the beginning.

**Comment by ALRubinger** [comment]
@tnozicka I think between the work done and the plugins updated, we can close this, +1?

**Comment by tnozicka** [comment]
@ALRubinger +1, we can close this. The new approach we took with catapult because of problems in Overview with first build solves even the N deployments case for free ;)
