### ISSUE TITLE
"browser" Profile activation on "tests" module appear to have no effect

### ISSUE THREAD

**Issue by ALRubinger** [redhat-kontinuity/catapult#32]
Always seems to be using "phantomjs" regardless of if the "chrome" or "firefox" profile is specified.

**Comment by starksm64** [comment]
Assign it to me. The problem is that I was just using htmlUnit directly since the WebDriver interface did not have access to lower level info that I thought I needed. Really all I need is to be able to get the html source, and I have a version working with the WebDriver interface, but I'll wait and create a pull request after the changes for #26 are merged.

**Comment by starksm64** [comment]
Pull request is #51

**Comment by ALRubinger** [comment]
Took @starksm64 work here and ported it into work done in #55 to move the UI testing to use WebDriver (though not supplied by Drone due to version-specific bugs in PhantomJS and our needing greater control over exact version used; see `WebDriverProviderHack`)
