### ISSUE TITLE
Integration tests succeeding, but not showing in the test report

### ISSUE THREAD

**Issue by ALRubinger** [redhat-kontinuity/catapult#54]
http://jenkins.distortion.origin.fabric8.io/job/catapult/3/testReport/

**Comment by ALRubinger** [comment]
Update on this, @sabre1041 ?

**Comment by sabre1041** [comment]
@ALRubinger cause of the bug determined. Issue seen on [here](https://github.com/redhat-kontinuity/catapult/blob/master/Jenkinsfile#L58) line

While running integration tests, test results are in the `failsafe-reports` folder instead of `surefire-reports` 

Tested in a local Jenkins environment. Due to the CI environment going down, been hampered doing a formal validation. Going to try to spin up an environment representative of the environment to validate and submit a PR

**Comment by ALRubinger** [comment]
Ah of course.

**Comment by ALRubinger** [comment]
cb88ec6
