### ISSUE TITLE
Add WebHook support to the OpenShiftService

### ISSUE THREAD

**Issue by ALRubinger** [redhat-kontinuity/catapult#57]
For @rimolive to validate.

I'm pulling some code to this effect out of the work done in #40 to isolate that task to the `GitHubService`.  Can we outline the requirement here for why the `OpenShiftService` needs:

```
/**
 * Return the Github WebHook from an application.
 *
 * @param namespace
 * @param applicationName
 * @return
 */
String getGithubWebhook(String namespace, String applicationName);
```

**Comment by ALRubinger** [comment]
The commit in which I removed this from #40 is here: 13bf9ba26b0dbd6f0d02d7015d4ed2c842d76d65

**Comment by rimolive** [comment]
I think there is a confusion with the term "GitHub webhook". Let me explain better.

From GitHub developer:
~~~
"Webhooks allow you to build or set up integrations which subscribe to certain events on GitHub.com. When one of those events is triggered, we'll send a HTTP POST payload to the webhook's configured URL. Webhooks can be used to update an external issue tracker, trigger CI builds, update a backup mirror, or even deploy to your production server. "
~~~
So as you can seem what GitHub does is send a HTTP POST to a URL with the event information(which are also described what events can be triggered). However, this URL is not generated by GitHub but by the external tool that will be triggered (which in our case is OpenShift). 

From OpenShift side, when you create the applications from the templates, they come with two kinds of Webhooks: the GitHub and the Generic webhooks. The only difference between them is GitHub webhook contains a secret to handle the payload. See https://docs.openshift.com/enterprise/3.1/dev_guide/builds.html#webhook-triggers

Based on that explanation, we need to get the Webhook URL information from the project(and this is another thing we need to handle since a single project can have one or more BuildConfig objects) and then use the GitHub API to add this Webhook to the repo.

Does that clarify the implementation I made for #40 ?

**Comment by ALRubinger** [comment]
Yep, totally clear.  My point was more about separation of concerns.

GitHubService deals with any API calls we make to GitHub.

OpenShiftService deals with any API calls we make to OpenShift.

The Core API and Impl are where we might get information about the
appropriate URL to use from the OpenShiftService and then call the
GitHubService to make a webhook out of it.

So this issue, #40, was about making GitHub webhooks.  What the value
should be is a separate piece that should be handled by the core impl,
based on a call to the OpenShiftService to see what it should be.

Is that more clear or am I missing something?

**Comment by rimolive** [comment]
Correct, that is the correct flow.

**Comment by ALRubinger** [comment]
Upstream in 64f2176a544d887d5eaf73725145133bca2bc31f
