### ISSUE TITLE
GitHubResourceIT must revoke OAuth app access before test run

### ISSUE THREAD

**Issue by ALRubinger** [redhat-kontinuity/catapult#93]
The GitHubResourceIT tests that we can log into GitHub via OAuth and grant access to an application; if the test user has already granted access, we skip over parts of the test execution.  Need to revoke access (if it exists) at the start, grant access for the test.  This will ensure the test is repeatable and not of variable execution.

**Comment by ALRubinger** [comment]
Depends really on #55 getting upstream; lots of relevant work there we'll want first to avoid a messy merge.

**Comment by ALRubinger** [comment]
Will require SPI support in `GitHubServiceSpi` to revoke access to a 3rdparty OAuth application: https://developer.github.com/v3/oauth_authorizations/#delete-a-grant

**Comment by ALRubinger** [comment]
@vinicius-martinez Wanna take a stab at this? :)

**Comment by vinicius-martinez** [comment]
@ALRubinger  sure.....I'll work on this one!

**Comment by ALRubinger** [comment]
Done, thanks for accepting the team invite. :)

**Comment by vinicius-martinez** [comment]
@ALRubinger  just to give you a feedback..I´lll work on this tomorrow (June 2).. I had to refresh/rebase both katapult and openshift repos (my old setup was based on CDK). Sorry for that!

**Comment by ALRubinger** [comment]
N/P, thanks. :)

**Comment by vinicius-martinez** [comment]
Hello @ALRubinger  

I've working on this issue for the last couple days, however, I would like to highlight/clarify a few issues before moving forward and make a few mistakes:

- since I've updated my environment (using ADB and remote WF10), when running the integration tests, I get the following results:

Results :

Failed tests: 
  CatapultResourceIT.shouldFling:143
  GitHubResourceIT.shouldHaveTokenAssociatedAfterOAuth:111

Tests run: 7, Failures: 2, Errors: 0, Skipped: 0

# Question 1: is this expected ? or is it something related to my local environment ?

If this is an expected issue, from my analysis these tests are failing due the following:

- org.kontinuity.catapult.test.GitHubResourceIT.performGitHubOAuth

*line 177
String html2 = driver.getPageSource();

This variable is assigned with the following value: "<html><head></head><body>No initiating state found in the session; potential in-the-middle attack</body></html>"

As we can see, it looks like the current implementation of github authentication is not working properly which is leading to this "Main in the middle" issue, therefore, the subsequent validations/actions will not work as expected:

*line 185
 try {
    final WebElement authorizeBtn = driver.findElement(By.name("authorize"));
    authorizeBtn.click();
    final String html3 = driver.getPageSource();
    if(log.isLoggable(Level.FINEST)) {
        log.finest(MessageFormat.format("Page#3 html: {0}\n", html3));
    }
} catch (NoSuchElementException e) {
    System.err.printf("No authorize button found on page2\n");
}

Question 2: should we review the current oauth authentication methods ?

Question 3: should we implement on both catapult-service-github-impl and catapult-service-github-api projects methods to validade/authenticate/revoke/grant and additional methods in order to manage github integration ?

Best regards,

**Comment by ALRubinger** [comment]
Out of date; we now integrate in Keycloak for tokens and auth
